spring:
  datasource:
    url: jdbc:h2:file:./data/timetrackingdb;DB_CLOSE_DELAY=-1;MODE=PostgreSQL;AUTO_SERVER=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console

# Keep Eureka config same as default profile
server:
  port: 8084

logging:
  level:
    org.hibernate.SQL: INFO
