server:
  port: 8082
spring:
  application:
    name: ai-prediction-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: health,info
app:
  jwt:
    secret: change-me-in-prod
